# Generated by Django 3.2.6 on 2021-11-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_alter_user_enrollment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_name',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
