# Generated by Django 3.2.6 on 2021-11-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_alter_user_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='file_name',
            field=models.FileField(upload_to=''),
        ),
    ]
