# Generated by Django 4.0 on 2021-12-12 16:54

from django.db import migrations, models
import enroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_alter_user_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('mca', 'MCA'), ('msc', 'M.Sc')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='file_name',
            field=models.FileField(upload_to=enroll.models.file_path_dir),
        ),
    ]
