# Generated by Django 4.0 on 2021-12-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_auto_20211212_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('', '--Select--'), ('MCA', 'MCA'), ('MSc', 'M.Sc')], default='', max_length=10),
        ),
    ]
