# Generated by Django 4.0 on 2021-12-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_alter_user_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.CharField(choices=[('', '--Select--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=2),
        ),
    ]
