# Generated by Django 3.2.6 on 2021-12-30 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_user_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_attendance_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_name', models.CharField(max_length=70)),
                ('student_name', models.CharField(default='', max_length=70)),
                ('enrollment_no', models.IntegerField(default=0)),
                ('subject', models.CharField(choices=[('', '--Select--'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('Reinforcement Learning', 'Reinforcement Learning'), ('Mathematical Foundation', 'Mathematical Foundation'), ('Computer Vision', 'Computer Vision'), ('Numerical Optimization', 'Numerical Optimization'), ('Advanced Python', 'Advanced Python'), ('Natural Language Processing', 'Natural Language Processing')], default='', max_length=50)),
                ('course', models.CharField(choices=[('', '--Select--'), ('MCA', 'Master In Computer Application'), ('MSc', 'Master In Science')], default='', max_length=10)),
                ('sem', models.CharField(choices=[('', '--Select--'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='', max_length=10)),
                ('batch_year', models.CharField(choices=[('', '--Select--'), ('2019-2020', '2019-2020'), ('2020-2021', '2020-2021'), ('2021-2022', '2021-2022'), ('2022-2023', '2022-2023')], default='', max_length=10)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='semester',
        ),
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(choices=[('', '--Select--'), ('MCA', 'Master In Computer Application'), ('MSc', 'Master In Science')], default='', max_length=10),
        ),
    ]
