# Generated by Django 4.0 on 2021-12-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_user_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='batch',
            field=models.CharField(choices=[('', '--Select--'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022')], default='', max_length=5),
        ),
    ]
