# Generated by Django 3.2.6 on 2021-12-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_auto_20211230_1242'),
        ('enroll', '0008_user_batch'),
    ]

    operations = [
    ]
